### ISSUE TITLE
Clarify confusing documentation

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/fgeo.plot#49]
Look for ways to clarify the documentation for users to now waste time and energy trying to figure out that the census and elevation data in `sp_elev()` should be form the same site. 

Relates to https://github.com/forestgeo/fgeo.plot/issues/47 (thanks @mcgregorian1 and @alyssaterrell).

**Comment by maurolepore** [comment]
@mcgregorian1 and @alyssaterrell, I'm using your feedback to improve `sp_elev()`. 

I'm thinking about the conditions that would make other users bump into the same problem so I can give them an informative hint and avoid wasting their time. Please see the warning at the bottom. 

* Do you think it would have helped you understand what was the issue and how to fix it yourselves?
* What suggestions for improvement do you have?
``` r
library(fgeo.plot)
library(tidyverse)

(census_from_scbi <- fgeo.biomass::scbi_tree1)
#> # A tibble: 40,283 x 20
#>    treeID stemID tag   StemTag sp    quadrat    gx    gy DBHID CensusID
#>     <int>  <int> <chr> <chr>   <chr> <chr>   <dbl> <dbl> <int>    <int>
#>  1      1      1 10079 1       libe  0104     3.70  73       1        1
#>  2      2      2 10168 1       libe  0103    17.3   58.9     3        1
#>  3      3      3 10567 1       libe  0110     9    197.      5        1
#>  4      4      4 12165 1       nysy  0122    14.2  428.      7        1
#>  5      5      5 12190 1       havi  0122     9.40 436.      9        1
#>  6      6      6 12192 1       havi  0122     1.30 434      13        1
#>  7      7      7 12212 1       unk   0123    17.8  447.     15        1
#>  8      8      8 12261 1       libe  0125    18    484.     17        1
#>  9      9      9 12456 1       vipr  0130    18    598.     19        1
#> 10     10     10 12551 1       astr  0132     5.60 628.     22        1
#> # ... with 40,273 more rows, and 10 more variables: dbh <dbl>, pom <chr>,
#> #   hom <dbl>, ExactDate <chr>, DFstatus <chr>, codes <chr>,
#> #   nostems <dbl>, date <dbl>, status <chr>, agb <dbl>

(elevation_from_luquillo <- fgeo.x::elevation$col)
#> # A tibble: 6,565 x 3
#>        x     y  elev
#>  * <int> <int> <dbl>
#>  1     0     0  364.
#>  2     0     5  364.
#>  3     0    10  363.
#>  4     0    15  363.
#>  5     0    20  363 
#>  6     0    25  363.
#>  7     0    30  363.
#>  8     0    35  363.
#>  9     0    40  363.
#> 10     0    45  364.
#> # ... with 6,555 more rows

three_species_from_scbi <- census_from_scbi %>% 
  add_count(sp, sort = TRUE) %>% 
  filter(sp %in% unique(sp)[1:3])

autoplot(sp_elev(three_species_from_scbi, elevation_from_luquillo))
#> Warning:   The datasets passed to `sp` and `elev` seem to have different dimensions.
#>   Are you sure they come from the same forest plot?
#>   * `sp` Guessing: plotdim = c(400, 640)
#>   * `elev` Guessing: plotdim = c(320, 500)
```

![](https://i.imgur.com/XzZNdnK.png)

Created on 2019-03-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by mcgregorian1** [comment]
Hi @maurolepore 

That warning would have been perfect actually - it tells us that there is a discrepancy between the two, and we would have picked up on it.

Perhaps the only thing I'd suggest is to add to the warning:

```r
autoplot(sp_elev(three_species_from_scbi, elevation))
#> Warning:   The datasets passed to `sp` and `elev` seem to have different dimensions.
#>   Are you sure they come from the same forest plot?
#>   * `sp` Guessing: plotdim = c(400, 640)
#>   * `elev` Guessing: plotdim = c(320, 500)
#>   Review help files for sp_elev
```
This assumes that in the help file for sp_elev, it's clear that the default dataset for elevation is from Luquillo.

In addition, perhaps a warning message that the "elevation" file must be in a certain format, and should not include any decimal degrees or UTM lat/lon coordinates?

**Comment by maurolepore** [comment]
Thanks! 

> Perhaps the only thing I'd suggest is to add to the warning: ... `Review help files for sp_elev`

Good idea. The warning now points to `?sp_elev()`.

> This assumes that in the help file for sp_elev, it's clear that the default dataset for elevation is from Luquillo.

I improved the documentation, but I prefer to rely on warnings than documentation because most users (including myself) read documentation only if they are stuck after a few quick attempts based on the examples.

![image](https://user-images.githubusercontent.com/5856545/53654480-d5303280-3c1b-11e9-81a8-d01901697860.png)

> In addition, perhaps a warning message that the "elevation" file must be in a certain format, and should not include any decimal degrees or UTM lat/lon coordinates?

I'm passing on this one. The warning has to be general enough that captures problems in any unit. Using lat/long is not the only way in which users can feed wrong units. For now I'll rely on the users noticing the discrepancy between the plotdimensions of `sp` and `elev`. (The example below pretends units in lat/lon)

Thanks!!!

``` r
library(fgeo.plot)
library(tidyverse)

census_from_scbi <- fgeo.biomass::scbi_tree1

elevation_from_scbi_in_lat_long <- fgeo.scbi::scbi_elevation %>% 
  mutate(
    # Multiplying by a large number to prettend that units are given in lat/lon
    gx = gx *1000,
    gy = gy *1000
  )

three_species_from_scbi <- census_from_scbi %>% 
  add_count(sp, sort = TRUE) %>% 
  filter(sp %in% unique(sp)[1:3])

autoplot(sp_elev(three_species_from_scbi, elevation_from_scbi_in_lat_long))
#> Warning:   The datasets passed to `sp` and `elev` seem to have different dimensions.
#>   Are you sure they come from the same forest plot? (see `?sp_elev()`)
#>   * `sp` Guessing: plotdim = c(400, 640)
#>   * `elev` Guessing: plotdim = c(4e+05, 640000)
```

![](https://i.imgur.com/c2FTm6f.png)

Created on 2019-03-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)
