### ISSUE TITLE
Dot size and topo lines

### ISSUE THREAD

**Issue by gonzalezeb** [forestgeo/fgeo.plot#51]
Hi @maurolepore 
I couldn't made these simple changes on species plots so I wrote this issue:

- how to change the dot's size ? For example, I tried adding into the function `autoplot` the words "size"or "pch" but none worked (aka no change in size, I want them really small):
_autoplot(
  sp_elev(small_census, elevation),
  fill = "blue", 
  size=5,
  hide_color_legend = TRUE
)_
- can the elevation 'water marks' for the topolines run parallel to such lines? 
- how can I change the color the topo lines to look all black?

**Comment by maurolepore** [comment]
Thanks @gonzalezeb for this issue.

I can answer your first and third question but if I do it now I will miss the opportunity to learn how most users search for information. Can you please describe your process? Could we chat on the phone or video?

`autoplot()` is a particularly tricky function and I likely need to re-structure its documentation.


I don't fully understand your second question. Do you want to move the legend position from the right to the top? Here is one example:

``` r
library(tidyverse)
library(fgeo.plot)

census <- fgeo.biomass::scbi_tree1 %>% 
  filter(sp == "libe")
elevation <- fgeo.scbi::scbi_elevation

# Legend on the right by default
autoplot(sp_elev(census, elevation))
```

![](https://i.imgur.com/CPf0vsM.png)

``` r

# Posiiton legend at the top (?ggplot2::theme())
autoplot(sp_elev(census, elevation)) + 
  theme(legend.position = "top")
```

![](https://i.imgur.com/xhwQx8s.png)

Created on 2019-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by gonzalezeb** [comment]
Thank you Mauro, to close this issue I will answer myself based on our conversation

-  I can modify the function `autoplot` following examples [here](https://forestgeo.github.io/fgeo.plot/reference/autoplot.sp_elev.html)
- I can also use [ggplot](https://www.rdocumentation.org/packages/ggplot2/versions/3.1.0) to make changes
